### ISSUE TITLE
Implement frontend interface to register multiple transferences

### ISSUE THREAD

**Issue by JSilversun** [JSilversun/cake_shop_ecommerce#15]
Is necessary to implement the UI to register multiple transferences **according to the mockup designed in #17** and **send the payment data with the format defined in #14**.

## Tasks
1. [ ] Create the `Successful payment page` according to the mockups
1. [ ] Create a form to register multiple transferences according to #3 and following the mockups
1. [ ] Implement validations according to the **Acceptance Criteria** of #3
1. [ ] Send a request to the backend endpoint with the order's payments with the data structure defined #14 (The endpoint URL is also defined in #14)
1. [ ] Display errors processed by the backend
1. [ ] Redirect the user to the `Successful payment page` if the backend response doesn't have errors 

## Acceptance Criteria:
This issue must follow all Acceptance Criteria defined in #3 (1-5)
