### ISSUE TITLE
Implement backend endpoint to register multiple transferences

### ISSUE THREAD

**Issue by JSilversun** [JSilversun/cake_shop_ecommerce#18]
Is necessary to create the backend endpoint to process multiple transferences. The data received by this endpoint and the response format are already defined in #14.

## Tasks
1. [ ] Create necessary database models according to <Database modeling issue>
1. [ ] Implement validations according to Acceptance Criteria defined in #3 (1-3)
1. [ ] Return formatted errors (if they occur) as defined in #14
1. [ ] Return formatted successful response (if there aren't any errors) as defined in #14

## Acceptance Criteria
This issue must follow the **Acceptance Criteria** defined in #3 (1-3), this means the backend must do all validations on its own regardless of the frontend validations in case these validations are bypassed.

**Note**: For the following validations criteria, please be aware that there are examples defined in #14 for successful and invalid scenarios, please use them for testing
1. The endpoint must be able to process the data with the structure defined in #14 and register all the transferences with `Waiting for confirmation` status
1. If any of the validations defined in #3 (1-3) the backend must return a response with errors according to the structure defined in #14
1. If all the transferences are valid according to Acceptance Criteria defined in #3, the backend will return a successful response with the format defined in #14
